[package]
name = "noot"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["debug", "tokio", "highlighter", "image"] }
tokio = { version = "1.43.0", features = ["fs", "full"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
discord-rich-presence = "0.2.5"
dirs = "6.0.0"
json5 = "0.4.1"
lazy_static = "1.5.0"
chrono = { version = "0.4.39", features = ["serde"] }
toml = "0.8.20"
nanoid = "0.4"
