[package]
name = "noot"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["debug", "tokio", "highlighter", "image"] }
tokio = { version = "1.43.0", features = ["fs", "full"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
discord-rich-presence = "0.2.5"
dirs = "6.0.0"
lazy_static = "1.5.0"
chrono = { version = "0.4.39", features = ["serde"] }
toml = "0.8.20"
nanoid = "0.4"
log = "0.4.26"
pretty_env_logger = "0.5.0"
env_logger = "0.11.6"
git-version = "0.3.9"
hashbrown = { version = "0.15.2", features = ["serde"] }
num_cpus = "1.16.0"
cocoon = "0.4.3"
bitflags = { version = "2.9.0", features = ["serde"] }
infer = "0.19"
keyring = { version = "3.6.2", features = ["tokio"] }
secrets = "1.2.0"
pbkdf2 = { version = "0.12.2", features = ["std"] }
sha2 = "0.10"
hmac = "0.12"
secp256k1 = "0.27"
zeroize = "1.6"
rand = "0.9.0"

[build-dependencies]
rand = "0.9.0"
