last-open = "091ZqEwsFMsDuyQ6"

[rpc]
enable = true
client-id = "1343225099834101810"
enable-idle = true



[[workspace]]
id = "091ZqEwsFMsDuyQ6"
name = "Default Workspace"
store = "git://git@github.com:NootApp/sample-workspace.git"
local-path = ":WSP_DIR:/default"
cd = "2025-03-01T17:16:18.383Z"
le = "2025-03-01T17:16:18.383Z"
flags = 0

[workspace.backup-strategy]
permit-remotes = ["origin"]

[workspace.rpc]
enable = false
enable-idle = false
show-current-file = false
show-workspace-name = false
